# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ADNeterworingASnapKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ADNeterworingASnapKit

  target 'ADNeterworingASnapKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ADNeterworingASnapKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'SnapKit'
pod 'MJExtension'
pod 'MJRefresh'
end


